### PR TITLE
show keyboard shortcut

### PR DESCRIPTION
**Pull request by Carreau**
In progress, @svurens, @jdfreder 

ping @cameronoelsen I currently use 2 colors to show the difference command/edit mode. But that probably not the right colors, nor the right visual clue. cc @ellisonbg. 

screen shot 2015-08-10 at 11 59 00

### CODE REVIEW

**Comment by ellisonbg** [comment]
Awesome! @jdfreder will be at Cal Poly this week working with @svurens and @cameronoelsen - Cameron can you have a look at the visual design on this stuff while Jon is there?

**Comment by Carreau** [comment]
I would also find a way to completely get rid of the dialog below, and get just the input-field and the proposal.  But that's technical.

**Comment by Carreau** [comment]
Ok, big refactoring, change keybindings to be accessible from edit-mode, 
Search by namespace so that custom extensions/actions are shown explicitly as extension. 

cmdp

**Comment by jdfreder** [comment]
This is really cool @Carreau , I like this!

**Comment by jdfreder** [comment]
Let us know when you're ready for a review.

**Comment by Carreau** [comment]
Still playing around, and using global, welcomed PRs that clean-up things.

You can try it if you likes.

On Mon, Aug 10, 2015 at 5:29 PM, Jonathan Frederic <notifications@github.com

**Comment by Carreau** [comment]
Grrr conflicts.... due to rebase. I might force push on other branch at some point.

**Pull request merged**
